# _*_ coding: utf-8_*_
#
# genral application route config:
# simplify the router config by dinamic load class
# by lwz7512
# @2016/05/17

import tornado.web

from foo import comm
from foo.ui import ui_amaze
from foo.ui import ui_cn
from foo.ui import ui_bootstrapmade
from foo.ui import ui_legend
from foo.ui import ui_weui
from foo.ui import ui_editor
from foo.ui import ui_blocks
from foo.ui import ui_gentelella
from foo.ui import ui_newsup
from foo.ui import ui_musik
from foo.ui import ui_bookpi
from foo.ui import ui_myplay
from foo.ui import ui_mateblog
from foo.ui import ui_cyberlife
from foo.ui import ui_tbmobile
from foo.ui import ui_icarus


def map():

    config = [

        # GET: 根据 HTTP header 收集客户端相关信息：是否手机、操作系统、浏览器等信息。
        (r'/', getattr(ui_blocks, 'BlocksHandler')),

        (r'/ui/weui', getattr(ui_weui, 'WeuiIndexHandler')),
        (r'/ui/weui/buttons', getattr(ui_weui, 'WeuiButtonsHandler')),
        (r'/ui/weui/cell', getattr(ui_weui, 'WeuiCellHandler')),
        (r'/ui/weui/form', getattr(ui_weui, 'WeuiFormHandler')),
        (r'/ui/weui/flex', getattr(ui_weui, 'WeuiFlexHandler')),
        (r'/ui/weui/toast', getattr(ui_weui, 'WeuiToastHandler')),
        (r'/ui/weui/dialog', getattr(ui_weui, 'WeuiDialogHandler')),
        (r'/ui/weui/progress', getattr(ui_weui, 'WeuiProgressHandler')),
        (r'/ui/weui/msg', getattr(ui_weui, 'WeuiMsgHandler')),
        (r'/ui/weui/article', getattr(ui_weui, 'WeuiArticleHandler')),
        (r'/ui/weui/action-sheet', getattr(ui_weui, 'WeuiActionSheetHandler')),
        (r'/ui/weui/icons', getattr(ui_weui, 'WeuiIconsHandler')),
        (r'/ui/weui/panel', getattr(ui_weui, 'WeuiPanelHandler')),
        (r'/ui/weui/navbar', getattr(ui_weui, 'WeuiNavbarHandler')),
        (r'/ui/weui/tabbar', getattr(ui_weui, 'WeuiTabbarHandler')),
        (r'/ui/weui/searchbar', getattr(ui_weui, 'WeuiSearchbarHandler')),
        (r'/ui/weui/toptip', getattr(ui_weui, 'WeuiToptipHandler')),
        (r'/ui/weui/loadmore', getattr(ui_weui, 'WeuiLoadmoreHandler')),
        (r'/ui/weui/slider', getattr(ui_weui, 'WeuiSliderHandler')),
        (r'/ui/weui/uploader', getattr(ui_weui, 'WeuiUploaderHandler')),
        (r'/ui/weui/badge', getattr(ui_weui, 'WeuiBadgeHandler')),
        (r'/ui/weui/footer', getattr(ui_weui, 'WeuiFooterHandler')),
        (r'/ui/weui/preview', getattr(ui_weui, 'WeuiPreviewHandler')),
        (r'/ui/weui/gallery', getattr(ui_weui, 'WeuiGalleryHandler')),
        (r'/ui/weui/ptr', getattr(ui_weui, 'WeuiPtrHandler')),
        (r'/ui/weui/infinite', getattr(ui_weui, 'WeuiInfiniteHandler')),
        (r'/ui/weui/picker', getattr(ui_weui, 'WeuiPickerHandler')),
        (r'/ui/weui/calendar', getattr(ui_weui, 'WeuiCalendarHandler')),
        (r'/ui/weui/city-picker', getattr(ui_weui, 'WeuiCityPickerHandler')),
        (r'/ui/weui/datetime-picker', getattr(ui_weui, 'WeuiDatetimePickerHandler')),
        (r'/ui/weui/swiper', getattr(ui_weui, 'WeuiSwiperHandler')),
        (r'/ui/weui/noti', getattr(ui_weui, 'WeuiNotiHandler')),
        (r'/ui/weui/select', getattr(ui_weui, 'WeuiSelectHandler')),
        (r'/ui/weui/popup', getattr(ui_weui, 'WeuiPopupHandler')),
        (r'/ui/weui/photo-browser', getattr(ui_weui, 'WeuiPhotoBrowserHandler')),


        (r'/ui/editor', getattr(ui_editor, 'EditorIndexHandler')),
        (r'/ui/editor/popular/full', getattr(ui_editor, 'EditorPopularFullHandler')),
        (r'/ui/editor/popular/toolbar_inline', getattr(ui_editor, 'EditorPopularToolbarInlineHandler')),
        (r'/ui/editor/popular/two_instances', getattr(ui_editor, 'EditorPopularTwoInstancesHandler')),
        (r'/ui/editor/popular/textarea', getattr(ui_editor, 'EditorPopularTextareaHandler')),
        (r'/ui/editor/popular/full_page', getattr(ui_editor, 'EditorPopularFullPageHandler')),
        (r'/ui/editor/popular/iframe', getattr(ui_editor, 'EditorPopularIframeHandler')),
        (r'/ui/editor/popular/disable_edit', getattr(ui_editor, 'EditorPopularDisableEditHandler')),
        (r'/ui/editor/popular/z_index', getattr(ui_editor, 'EditorPopularZindexHandler')),
        (r'/ui/editor/popular/init_on_click', getattr(ui_editor, 'EditorPopularInitOnClickHandler')),
        (r'/ui/editor/popular/toolbar_buttons', getattr(ui_editor, 'EditorPopularToolbarButtonsHandler')),
        (r'/ui/editor/popular/disable_paragraphs', getattr(ui_editor, 'EditorPopularDisableParagraphsHandler')),
        (r'/ui/editor/3rd-party/aviary/index', getattr(ui_editor, 'Editor3rdPartyAviaryIndexHandler')),
        (r'/ui/editor/3rd-party/bootstrap/grid', getattr(ui_editor, 'Editor3rdPartyBootstrapGridHandler')),
        (r'/ui/editor/3rd-party/bootstrap/lists', getattr(ui_editor, 'Editor3rdPartyBootstrapListsHandler')),
        (r'/ui/editor/3rd-party/bootstrap/modal', getattr(ui_editor, 'Editor3rdPartyBootstrapModalHandler')),
        (r'/ui/editor/3rd-party/jquery/mobile', getattr(ui_editor, 'Editor3rdPartyJqueryMobileHandler')),
        (r'/ui/editor/3rd-party/jquery/ui_modal', getattr(ui_editor, 'Editor3rdPartyJqueryUimodalHandler')),
        (r'/ui/editor/3rd-party/at_js', getattr(ui_editor, 'Editor3rdPartyAtJsHandler')),
        (r'/ui/editor/3rd-party/code-mirror', getattr(ui_editor, 'Editor3rdPartyCodeMirrorHandler')),
        (r'/ui/editor/3rd-party/require_js/index', getattr(ui_editor, 'Editor3rdPartyRequireIndexHandler')),
        (r'/ui/editor/3rd-party/spell-checker', getattr(ui_editor, 'Editor3rdPartySpellCheckerHandler')),
        (r'/ui/editor/api/init_destroy', getattr(ui_editor, 'EditorApiInitDestroyHandler')),
        (r'/ui/editor/api/get_html', getattr(ui_editor, 'EditorApiGetHtmlHandler')),
        (r'/ui/editor/api/insert_html', getattr(ui_editor, 'EditorApiInsertHtmlHandler')),
        (r'/ui/editor/api/selection', getattr(ui_editor, 'EditorApiSelectionHandler')),
        (r'/ui/editor/api/live_content_preview', getattr(ui_editor, 'EditorApiLiveContentPreviewHandler')),
        (r'/ui/editor/api/live_code_preview', getattr(ui_editor, 'EditorApiLiveCodePreviewHandler')),
        (r'/ui/editor/international/direction_rtl', getattr(ui_editor, 'EditorInternationalDirectionRtlHandler')),
        (r'/ui/editor/international/language', getattr(ui_editor, 'EditorInternationalLanguageHandler')),
        (r'/ui/editor/international/rtl_ltr_buttons', getattr(ui_editor, 'EditorInternationalRtlLtrButtonsHandler')),
        (r'/ui/editor/buttons/custom_buttons', getattr(ui_editor, 'EditorButtonsCustomButtonsHandler')),
        (r'/ui/editor/buttons/custom_dropdown', getattr(ui_editor, 'EditorButtonsCustomDropdownHandler')),
        (r'/ui/editor/buttons/external_button', getattr(ui_editor, 'EditorButtonsExternalButtonHandler')),
        (r'/ui/editor/buttons/subscript_superscript', getattr(ui_editor, 'EditorButtonsSubscriptSuperscriptHandler')),
        (r'/ui/editor/events/blur_focus', getattr(ui_editor, 'EditorEventsBlurFocusHandler')),
        (r'/ui/editor/events/content_changed', getattr(ui_editor, 'EditorEventsContentChangedHandler')),
        (r'/ui/editor/events/drop', getattr(ui_editor, 'EditorEventsDropHandler')),
        (r'/ui/editor/events/image_removed', getattr(ui_editor, 'EditorEventsImageRemovedHandler')),
        (r'/ui/editor/events/initialized_destroy', getattr(ui_editor, 'EditorEventsInitializedDestroyHandler')),
        (r'/ui/editor/image/custom_button', getattr(ui_editor, 'EditorImageCustomButtonHandler')),
        (r'/ui/editor/image/image_styles', getattr(ui_editor, 'EditorImageImageStylesHandler')),
        (r'/ui/editor/image/default_width', getattr(ui_editor, 'EditorImageDefaultWidthHandler')),
        (r'/ui/editor/image/insert_base64', getattr(ui_editor, 'EditorImageInsertBase64Handler')),
        (r'/ui/editor/init_inside_iframe/basic', getattr(ui_editor, 'EditorInitInsideIframeBasicHandler')),
        (r'/ui/editor/init_inside_iframe/inline', getattr(ui_editor, 'EditorInitInsideIframeInlineHandler')),
        (r'/ui/editor/init_on_click/basic', getattr(ui_editor, 'EditorInitOnClickBasicHandler')),
        (r'/ui/editor/init_on_click/inline', getattr(ui_editor, 'EditorInitOnClickInlineHandler')),
        (r'/ui/editor/init_on_click/two_editors', getattr(ui_editor, 'EditorInitOnClickTwoEditorsHandler')),
        (r'/ui/editor/initialization/init_on_click', getattr(ui_editor, 'EditorInitializationInitOnClickHandler')),
        (r'/ui/editor/initialization/init_on_button', getattr(ui_editor, 'EditorInitializationInitOnButtonHandler')),
        (r'/ui/editor/initialization/init_on_link', getattr(ui_editor, 'EditorInitializationInitOnLinkHandler')),
        (r'/ui/editor/initialization/init_on_image', getattr(ui_editor, 'EditorInitializationInitOnImageHandler')),
        (r'/ui/editor/initialization/init_on_h1', getattr(ui_editor, 'EditorInitializationInitOnH1Handler')),
        (r'/ui/editor/initialization/initialized_event', getattr(ui_editor, 'EditorInitializationInitializedEventHandler')),
        (r'/ui/editor/initialization/edit_in_popup', getattr(ui_editor, 'EditorInitializationEditInPopupHandler')),
        (r'/ui/editor/link/link_styles', getattr(ui_editor, 'EditorLinkLinkStylesHandler')),
        (r'/ui/editor/link/predefined_links', getattr(ui_editor, 'EditorLinkPredefinedLinksHandler')),
        (r'/ui/editor/link/custom_validation', getattr(ui_editor, 'EditorLinkCustomValidationHandler')),
        (r'/ui/editor/plugins/line_breaker', getattr(ui_editor, 'EditorPluginsLineBreakerHandler')),
        (r'/ui/editor/plugins/quick_insert', getattr(ui_editor, 'EditorPluginsQuickInsertHandler')),
        (r'/ui/editor/plugins/char_counter', getattr(ui_editor, 'EditorPluginsCharCounterHandler')),
        (r'/ui/editor/plugins/full_screen', getattr(ui_editor, 'EditorPluginsFullScreenHandler')),
        (r'/ui/editor/popups/colors', getattr(ui_editor, 'EditorPopupsColorsHandler')),
        (r'/ui/editor/popups/emoticons', getattr(ui_editor, 'EditorPopupsEmoticonsHandler')),
        (r'/ui/editor/popups/custom', getattr(ui_editor, 'EditorPopupsCustomHandler')),
        (r'/ui/editor/styling/font_family', getattr(ui_editor, 'EditorStylingFontFamilyHandler')),
        (r'/ui/editor/styling/inline', getattr(ui_editor, 'EditorStylingInlineHandler')),
        (r'/ui/editor/styling/paragraph', getattr(ui_editor, 'EditorStylingParagraphHandler')),
        (r'/ui/editor/styling/placeholder', getattr(ui_editor, 'EditorStylingPlaceholderHandler')),
        (r'/ui/editor/styling/height', getattr(ui_editor, 'EditorStylingHeightHandler')),
        (r'/ui/editor/styling/adjustable_height', getattr(ui_editor, 'EditorStylingAdjustableHeightHandler')),
        (r'/ui/editor/styling/width', getattr(ui_editor, 'EditorStylingWidthHandler')),
        (r'/ui/editor/themes/dark', getattr(ui_editor, 'EditorThemesDarkHandler')),
        (r'/ui/editor/themes/gray', getattr(ui_editor, 'EditorThemesGrayHandler')),
        (r'/ui/editor/themes/red', getattr(ui_editor, 'EditorThemesRedHandler')),
        (r'/ui/editor/themes/royal', getattr(ui_editor, 'EditorThemesRoyalHandler')),
        (r'/ui/editor/table/nested', getattr(ui_editor, 'EditorTableNestedHandler')),
        (r'/ui/editor/table/resize', getattr(ui_editor, 'EditorTableResizeHandler')),
        (r'/ui/editor/table/insert_helper', getattr(ui_editor, 'EditorTableInsertHelperHandler')),
        (r'/ui/editor/table/style', getattr(ui_editor, 'EditorTableStyleHandler')),
        (r'/ui/editor/table/cell_style', getattr(ui_editor, 'EditorTableCellStyleHandler')),
        (r'/ui/editor/toolbar/inline', getattr(ui_editor, 'EditorToolbarInlineHandler')),
        (r'/ui/editor/toolbar/sticky', getattr(ui_editor, 'EditorToolbarStickyHandler')),
        (r'/ui/editor/toolbar/buttons', getattr(ui_editor, 'EditorToolbarButtonsHandler')),
        (r'/ui/editor/toolbar/external', getattr(ui_editor, 'EditorToolbarExternalHandler')),
        (r'/ui/editor/toolbar/external_inline', getattr(ui_editor, 'EditorToolbarExternalInlineHandler')),
        (r'/ui/editor/toolbar/bottom', getattr(ui_editor, 'EditorToolbarBottomHandler')),
        (r'/ui/editor/toolbar/offset', getattr(ui_editor, 'EditorToolbarOffsetHandler')),
        (r'/ui/editor/toolbar/bottom_offset', getattr(ui_editor, 'EditorToolbarBottomOffsetHandler')),
        (r'/ui/editor/toolbar/show_selection', getattr(ui_editor, 'EditorToolbarShowSelectionHandler')),
        (r'/ui/editor/toolbar/inline_selection', getattr(ui_editor, 'EditorToolbarInlineSelectionHandler')),
        (r'/ui/editor/paragraph_modes/enter_br', getattr(ui_editor, 'EditorParagraphModesEnterBrHandler')),
        (r'/ui/editor/paragraph_modes/enter_div', getattr(ui_editor, 'EditorParagraphModesEnterDivHandler')),
        (r'/ui/editor/paragraph_modes/enter_p', getattr(ui_editor, 'EditorParagraphModesEnterpHandler')),
        (r'/ui/editor/misc/scrollable_container', getattr(ui_editor, 'EditorMiscScrollableContainerHandler')),
        (r'/ui/editor/misc/scrollable_container_inline', getattr(ui_editor, 'EditormiscScrollableContainerInlineHandler')),
        (r'/ui/editor/typing/tab', getattr(ui_editor, 'EditorTypingTabHandler')),
        (r'/ui/editor/typing/shortcuts', getattr(ui_editor, 'EditorTypingShortcutsHandler')),
        (r'/ui/editor/typing/keep_format', getattr(ui_editor, 'EditorTypingKeepFormatHandler')),
        (r'/ui/editor/paste/plain', getattr(ui_editor, 'EditorPastePlainHandler')),
        (r'/ui/editor/paste/attrs', getattr(ui_editor, 'EditorPasteAttrsHandler')),
        (r'/ui/editor/paste/tags', getattr(ui_editor, 'EditorPasteTagsHandler')),

        (r'/ui/blocks', getattr(ui_blocks, 'BlocksHandler')),
        (r'/ui/blocks/index', getattr(ui_blocks, 'BlocksIndexHandler')),
        (r'/ui/blocks/call_to_action', getattr(ui_blocks, 'BlocksCallToActionHandler')),
        (r'/ui/blocks/contacts', getattr(ui_blocks, 'BlocksContactsHandler')),
        (r'/ui/blocks/contents', getattr(ui_blocks, 'BlocksContentsHandler')),
        (r'/ui/blocks/features', getattr(ui_blocks, 'BlocksFeaturesHandler')),
        (r'/ui/blocks/footers', getattr(ui_blocks, 'BlocksFootersHandler')),
        (r'/ui/blocks/forms', getattr(ui_blocks, 'BlocksFormsHandler')),
        (r'/ui/blocks/headers', getattr(ui_blocks, 'BlocksHeadersHandler')),
        (r'/ui/blocks/pricings', getattr(ui_blocks, 'BlocksPricingsHandler')),
        (r'/ui/blocks/teams', getattr(ui_blocks, 'BlocksTeamsHandler')),
        (r'/ui/blocks/testimonials', getattr(ui_blocks, 'BlocksTestimonialsHandler')),

        (r'/ui/gentelella', getattr(ui_gentelella, 'GentelellaIndexHandler')),
        (r'/ui/gentelella/index2', getattr(ui_gentelella, 'GentelellaIndex2Handler')),
        (r'/ui/gentelella/index3', getattr(ui_gentelella, 'GentelellaIndex3Handler')),
        (r'/ui/gentelella/form', getattr(ui_gentelella, 'GentelellaFormHandler')),
        (r'/ui/gentelella/form_advanced', getattr(ui_gentelella, 'GentelellaFormAdvancedHandler')),
        (r'/ui/gentelella/form_validation', getattr(ui_gentelella, 'GentelellaFormValidationdHandler')),
        (r'/ui/gentelella/form_wizards', getattr(ui_gentelella, 'GentelellaFormWizardsdHandler')),
        (r'/ui/gentelella/form_upload', getattr(ui_gentelella, 'GentelellaFormUploadHandler')),
        (r'/ui/gentelella/form_buttons', getattr(ui_gentelella, 'GentelellaFormButtonsHandler')),
        (r'/ui/gentelella/general_elements', getattr(ui_gentelella, 'GentelellaGeneralElementsHandler')),
        (r'/ui/gentelella/media_gallery', getattr(ui_gentelella, 'GentelellaMediaGalleryHandler')),
        (r'/ui/gentelella/typography', getattr(ui_gentelella, 'GentelellaTypographyHandler')),
        (r'/ui/gentelella/icons', getattr(ui_gentelella, 'GentelellaIconsHandler')),
        (r'/ui/gentelella/glyphicons', getattr(ui_gentelella, 'GentelellaGlyphiconsHandler')),
        (r'/ui/gentelella/widgets', getattr(ui_gentelella, 'GentelellaWidgetsHandler')),
        (r'/ui/gentelella/invoice', getattr(ui_gentelella, 'GentelellaInvoiceHandler')),
        (r'/ui/gentelella/inbox', getattr(ui_gentelella, 'GentelellaInboxHandler')),
        (r'/ui/gentelella/calendar', getattr(ui_gentelella, 'GentelellaCalendarHandler')),
        (r'/ui/gentelella/tables', getattr(ui_gentelella, 'GentelellaTablesHandler')),
        (r'/ui/gentelella/tables_dynamic', getattr(ui_gentelella, 'GentelellaTablesDynamicHandler')),
        (r'/ui/gentelella/chartjs', getattr(ui_gentelella, 'GentelellaChartjsHandler')),
        (r'/ui/gentelella/chartjs2', getattr(ui_gentelella, 'GentelellaChartjs2Handler')),
        (r'/ui/gentelella/morisjs', getattr(ui_gentelella, 'GentelellaMorisjsHandler')),
        (r'/ui/gentelella/echarts', getattr(ui_gentelella, 'GentelellaEchartsHandler')),
        (r'/ui/gentelella/other_charts', getattr(ui_gentelella, 'GentelellaOtherChartsHandler')),
        (r'/ui/gentelella/fixed_sidebar', getattr(ui_gentelella, 'GentelellaFixedSidebarHandler')),
        (r'/ui/gentelella/fixed_footer', getattr(ui_gentelella, 'GentelellaFixedFooterHandler')),
        (r'/ui/gentelella/e_commerce', getattr(ui_gentelella, 'GentelellaEcommerceHandler')),
        (r'/ui/gentelella/projects', getattr(ui_gentelella, 'GentelellaProjectsHandler')),
        (r'/ui/gentelella/project_detail', getattr(ui_gentelella, 'GentelellaProjectDetailHandler')),
        (r'/ui/gentelella/contacts', getattr(ui_gentelella, 'GentelellaContactsHandler')),
        (r'/ui/gentelella/profile', getattr(ui_gentelella, 'GentelellaProfileHandler')),
        (r'/ui/gentelella/page_403', getattr(ui_gentelella, 'GentelellaPage403Handler')),
        (r'/ui/gentelella/page_404', getattr(ui_gentelella, 'GentelellaPage404Handler')),
        (r'/ui/gentelella/page_500', getattr(ui_gentelella, 'GentelellaPage500Handler')),
        (r'/ui/gentelella/plain_page', getattr(ui_gentelella, 'GentelellaPlainPageHandler')),
        (r'/ui/gentelella/login', getattr(ui_gentelella, 'GentelellaLoginHandler')),
        (r'/ui/gentelella/pricing_tables', getattr(ui_gentelella, 'GentelellaPricingTablesHandler')),
        (r'/ui/gentelella/level2', getattr(ui_gentelella, 'GentelellaLevel2Handler')),


        (r'/ui/newsup/index', getattr(ui_newsup, 'NewsupIndexHandler')),
        (r'/ui/newsup/author', getattr(ui_newsup, 'NewsupAuthorHandler')),
        (r'/ui/newsup/media', getattr(ui_newsup, 'NewsupMediaHandler')),
        (r'/ui/newsup/shortcodes', getattr(ui_newsup, 'NewsupShortcodesHandler')),
        (r'/ui/newsup/contact', getattr(ui_newsup, 'NewsupContactHandler')),
        (r'/ui/newsup/account', getattr(ui_newsup, 'NewsupAccountHandler')),
        (r'/ui/newsup/item-detail', getattr(ui_newsup, 'NewsupItemDetailHandler')),
        (r'/ui/newsup/new', getattr(ui_newsup, 'NewsupNewHandler')),
        (r'/ui/newsup/register', getattr(ui_newsup, 'NewsupRegisterHandler')),
        (r'/ui/newsup/category', getattr(ui_newsup, 'NewsupCategoryHandler')),


        (r'/ui/musik/index', getattr(ui_musik, 'MusikIndexHandler')),
        (r'/ui/musik/genres', getattr(ui_musik, 'MusikGenresHandler')),
        (r'/ui/musik/events', getattr(ui_musik, 'MusikEventsHandler')),
        (r'/ui/musik/listen', getattr(ui_musik, 'MusikListenHandler')),
        (r'/ui/musik/video', getattr(ui_musik, 'MusikVideoHandler')),
        (r'/ui/musik/video-detail', getattr(ui_musik, 'MusikVideoDetailHandler')),
        (r'/ui/musik/layout-color', getattr(ui_musik, 'MusikLayoutColorHandler')),
        (r'/ui/musik/layout-boxed', getattr(ui_musik, 'MusikLayoutBoxedHandler')),
        (r'/ui/musik/layout-fluid', getattr(ui_musik, 'MusikLayoutFluidHandler')),
        (r'/ui/musik/buttons', getattr(ui_musik, 'MusikButtonsHandler')),
        (r'/ui/musik/icons', getattr(ui_musik, 'MusikIconsHandler')),
        (r'/ui/musik/grid', getattr(ui_musik, 'MusikGridHandler')),
        (r'/ui/musik/widgets', getattr(ui_musik, 'MusikWidgetsHandler')),
        (r'/ui/musik/components', getattr(ui_musik, 'MusikComponentsHandler')),
        (r'/ui/musik/list', getattr(ui_musik, 'MusikListHandler')),
        (r'/ui/musik/table-static', getattr(ui_musik, 'MusikTableStaticHandler')),
        (r'/ui/musik/table-datatable', getattr(ui_musik, 'MusikTableDatatableHandler')),
        (r'/ui/musik/form-elements', getattr(ui_musik, 'MusikFormElementsHandler')),
        (r'/ui/musik/form-validation', getattr(ui_musik, 'MusikFormValidationHandler')),
        (r'/ui/musik/form-wizard', getattr(ui_musik, 'MusikFormWizardHandler')),
        (r'/ui/musik/chart', getattr(ui_musik, 'MusikChartHandler')),
        (r'/ui/musik/portlet', getattr(ui_musik, 'MusikPortletHandler')),
        (r'/ui/musik/timeline', getattr(ui_musik, 'MusikTimelineHandler')),
        (r'/ui/musik/profile', getattr(ui_musik, 'MusikProfileHandler')),
        (r'/ui/musik/blog', getattr(ui_musik, 'MusikBlogHandler')),
        (r'/ui/musik/invoice', getattr(ui_musik, 'MusikInvoiceHandler')),
        (r'/ui/musik/gmap', getattr(ui_musik, 'MusikGmapHandler')),
        (r'/ui/musik/jvectormap', getattr(ui_musik, 'MusikJvectormapHandler')),
        (r'/ui/musik/signin', getattr(ui_musik, 'MusikSigninHandler')),
        (r'/ui/musik/signup', getattr(ui_musik, 'MusikSignupHandler')),
        (r'/ui/musik/404', getattr(ui_musik, 'Musik404Handler')),
        (r'/ui/musik/docs', getattr(ui_musik, 'MusikDocsHandler')),
        (r'/ui/musik/modal-lockme', getattr(ui_musik, 'MusikModalLockmeHandler')),


        (r'/ui/bookpi/index', getattr(ui_bookpi, 'BookpiIndexHandler')),
        (r'/ui/bookpi/upload', getattr(ui_bookpi, 'BookpiUploadHandler')),
        (r'/ui/bookpi/download', getattr(ui_bookpi, 'BookpiDownloadHandler')),
        (r'/ui/bookpi/hot', getattr(ui_bookpi, 'BookpiHotHandler')),
        (r'/ui/bookpi/category', getattr(ui_bookpi, 'BookpiCategoryHandler')),
        (r'/ui/bookpi/new-books', getattr(ui_bookpi, 'BookpiNewBookslHandler')),
        (r'/ui/bookpi/book-detail', getattr(ui_bookpi, 'BookpiBookDetailHandler')),
        (r'/ui/bookpi/set-wifi', getattr(ui_bookpi, 'BookpiSetWifiHandler')),


        (r'/ui/myplay/index', getattr(ui_myplay, 'MyplayIndexHandler')),
        (r'/ui/myplay/shows', getattr(ui_myplay, 'MyplayShowsHandler')),
        (r'/ui/myplay/history', getattr(ui_myplay, 'MyplayHistoryHandler')),
        (r'/ui/myplay/movies', getattr(ui_myplay, 'MyplayMoviesHandler')),
        (r'/ui/myplay/sports', getattr(ui_myplay, 'MyplaySportsHandler')),
        (r'/ui/myplay/news', getattr(ui_myplay, 'MyplayNewsHandler')),
        (r'/ui/myplay/upload', getattr(ui_myplay, 'MyplayUploadHandler')),
        (r'/ui/myplay/about', getattr(ui_myplay, 'MyplayAboutHandler')),
        (r'/ui/myplay/press', getattr(ui_myplay, 'MyplayPressHandler')),
        (r'/ui/myplay/copyright', getattr(ui_myplay, 'MyplayCopyrightHandler')),
        (r'/ui/myplay/creators', getattr(ui_myplay, 'MyplayCreatorsHandler')),
        (r'/ui/myplay/developers', getattr(ui_myplay, 'MyplayDevelopersHandler')),
        (r'/ui/myplay/terms', getattr(ui_myplay, 'MyplayTermsHandler')),
        (r'/ui/myplay/privacy', getattr(ui_myplay, 'MyplayPrivacyHandler')),
        (r'/ui/myplay/try', getattr(ui_myplay, 'MyplayTryHandler')),
        (r'/ui/myplay/single', getattr(ui_myplay, 'MyplaySingleHandler')),


        (r'/ui/mateblog/index', getattr(ui_mateblog, 'MateblogIndexHandler')),
        (r'/ui/mateblog/home-2', getattr(ui_mateblog, 'MateblogHome2Handler')),
        (r'/ui/mateblog/home-3', getattr(ui_mateblog, 'MateblogHome3Handler')),
        (r'/ui/mateblog/home-4', getattr(ui_mateblog, 'MateblogHome4Handler')),
        (r'/ui/mateblog/home-5', getattr(ui_mateblog, 'MateblogHome5Handler')),
        (r'/ui/mateblog/single-left-sidebar', getattr(ui_mateblog, 'MateblogSingleLeftSidebarHandler')),
        (r'/ui/mateblog/single', getattr(ui_mateblog, 'MateblogSingleHandler')),
        (r'/ui/mateblog/about', getattr(ui_mateblog, 'MateblogAboutHandler')),
        (r'/ui/mateblog/contact', getattr(ui_mateblog, 'MateblogContactHandler')),

        # mobile-taobao
        (r'/ui/tbmobile/index', getattr(ui_tbmobile, 'TbmobileIndexHandler')),
        (r'/ui/tbmobile/news', getattr(ui_tbmobile, 'TbmobileNewsHandler')),
        (r'/ui/tbmobile/category', getattr(ui_tbmobile, 'TbmobileCategoryHandler')),
        (r'/ui/tbmobile/goodlist', getattr(ui_tbmobile, 'TbmobileGoodlistHandler')),
        (r'/ui/tbmobile/detail', getattr(ui_tbmobile, 'TbmobileDetailHandler')),
        (r'/ui/tbmobile/newsdetail', getattr(ui_tbmobile, 'TbmobileNewsdetailHandler')),
        (r'/ui/tbmobile/orders', getattr(ui_tbmobile, 'TbmobileOrdersHandler')),
        (r'/ui/tbmobile/shopcar', getattr(ui_tbmobile, 'TbmobileShopcarHandler')),
        (r'/ui/tbmobile/search', getattr(ui_tbmobile, 'TbmobileSearchHandler')),
        (r'/ui/tbmobile/user', getattr(ui_tbmobile, 'TbmobileUserHandler')),
        (r'/ui/tbmobile/user/bonus', getattr(ui_tbmobile, 'TbmobileUserBonusHandler')),

        (r'/legend', getattr(ui_legend, 'LegendIndexHandler')),
        (r'/legend/article', getattr(ui_legend, 'LegendArticleHandler')),
        (r'/legend/product', getattr(ui_legend, 'LegendProductHandler')),
        (r'/legend/moment', getattr(ui_legend, 'LegendMomentHandler')),
        (r'/legend/moment/add', getattr(ui_legend, 'LegendAddMomentHandler')),
        (r'/legend/comment/add', getattr(ui_legend, 'LegendAddCommentHandler')),
        (r'/legend/product/place-order', getattr(ui_legend, 'LegendProductPlaceOrderHandler')),
        (r'/legend/product/place-order-success', getattr(ui_legend, 'LegendProductPlaceOrderSuccessHandler')),

        (r'/uicn', getattr(ui_cn, 'UicnIndexHandler')),
        (r'/uicn/list', getattr(ui_cn, 'UicnListHandler')),
        (r'/uicn/exp', getattr(ui_cn, 'UicnExpHandler')),
        (r'/uicn/book', getattr(ui_cn, 'UicnBookHandler')),
        (r'/uicn/study', getattr(ui_cn, 'UicnStudyHandler')),
        (r'/uicn/game', getattr(ui_cn, 'UicnGameHandler')),
        (r'/uicn/peixun', getattr(ui_cn, 'UicnPeixunHandler')),
        (r'/uicn/topic', getattr(ui_cn, 'UicnTopicHandler')),
        (r'/uicn/online', getattr(ui_cn, 'UicnOnlineHandler')),
        (r'/uicn/zhaopin', getattr(ui_cn, 'UicnZhaopinHandler')),
        # 列表以及内容页
        (r'/uicn/content', getattr(ui_cn, 'UicnContentHandler')),
        (r'/uicn/zhaopin/cont', getattr(ui_cn, 'UicnZhaopinContHandler')),
        # 认证页面
        (r'/uicn/cert', getattr(ui_cn, 'UicnCertHandler')),

        # 注册 登录 找回
        (r'/auth/login', getattr(ui_cn, 'AuthLoginHandler')),
        (r'/auth/getpass', getattr(ui_cn, 'AuthGetpassHandler')),
        (r'/auth/reg', getattr(ui_cn, 'AuthRegHandler')),
        (r'/auth/findpassbymail', getattr(ui_cn, 'AuthFindpassHandler')),
        (r'/auth/changepass', getattr(ui_cn, 'AuthChangepassHandler')),
        (r'/auth/editsuccess', getattr(ui_cn, 'AuthEditsuccessHandler')),
        #  个人中心页
        (r'/uicn/self', getattr(ui_cn, 'UicnSelfHandler')),

        (r'/amazeui', getattr(ui_amaze, 'AmazeIndexHandler')),
        (r'/amazeui/1', getattr(ui_amaze, 'AmazeIndex1Handler')),
        (r'/amazeui/2', getattr(ui_amaze, 'AmazeIndex2Handler')),
        (r'/amazeui/3', getattr(ui_amaze, 'AmazeIndex3Handler')),
        (r'/amazeui/4', getattr(ui_amaze, 'AmazeIndex4Handler')),
        (r'/amazeui/5', getattr(ui_amaze, 'AmazeIndex5Handler')),
        (r'/amazeui/6', getattr(ui_amaze, 'AmazeIndex6Handler')),
        (r'/amazeui/7', getattr(ui_amaze, 'AmazeIndex7Handler')),
        (r'/amazeui/8', getattr(ui_amaze, 'AmazeIndex8Handler')),
        (r'/amazeui/9', getattr(ui_amaze, 'AmazeIndex9Handler')),
        (r'/amazeui/10', getattr(ui_amaze, 'AmazeIndex10Handler')),
        (r'/amazeui/11', getattr(ui_amaze, 'AmazeIndex11Handler')),
        (r'/amazeui/12', getattr(ui_amaze, 'AmazeIndex12Handler')),
        (r'/amazeui/13', getattr(ui_amaze, 'AmazeIndex13Handler')),
        (r'/amazeui/14', getattr(ui_amaze, 'AmazeIndex14Handler')),

        (r'/bootstrapmade/one-page', getattr(ui_bootstrapmade, 'BootstrapmadeOnePageHandler')),
        (r'/bootstrapmade/butterfly', getattr(ui_bootstrapmade, 'BootstrapmadeButterflyHandler')),
        (r'/bootstrapmade/coming-soon', getattr(ui_bootstrapmade, 'BootstrapmadeComingSoonHandler')),
        (r'/bootstrapmade/delicious', getattr(ui_bootstrapmade, 'BootstrapmadeDeliciousHandler')),
        (r'/bootstrapmade/knight', getattr(ui_bootstrapmade, 'BootstrapmadeKnightHandler')),
        (r'/bootstrapmade/laura', getattr(ui_bootstrapmade, 'BootstrapmadeLauraHandler')),
        (r'/bootstrapmade/medilab', getattr(ui_bootstrapmade, 'BootstrapmadeMedilabHandler')),
        (r'/bootstrapmade/mentor', getattr(ui_bootstrapmade, 'BootstrapmadeMentorHandler')),
        (r'/bootstrapmade/squad', getattr(ui_bootstrapmade, 'BootstrapmadeSquadHandler')),


        (r'/ui/cyberlife/index', getattr(ui_cyberlife, 'CyberlifeIndexHandler')),
        (r'/ui/cyberlife/about', getattr(ui_cyberlife, 'CyberlifeAboutHandler')),
        (r'/ui/cyberlife/contact', getattr(ui_cyberlife, 'CyberlifeContactHandler')),
        (r'/ui/cyberlife/single', getattr(ui_cyberlife, 'CyberlifeSingleHandler')),
        (r'/ui/cyberlife/categories', getattr(ui_cyberlife, 'CyberlifeCategoriesHandler')),
        (r'/ui/cyberlife/tags', getattr(ui_cyberlife, 'CyberlifeTagsHandler')),


		(r'/ui/icarus', getattr(ui_icarus, 'IcarusIndexHandler')),
		(r'/ui/icarus/categories/articles', getattr(ui_icarus, 'IcarusCategoryArticlesHandler')),
		(r'/ui/icarus/categories', getattr(ui_icarus, 'IcarusCategoriesHandler')),
		(r'/ui/icarus/tags', getattr(ui_icarus, 'IcarusTagsHandler')),
		(r'/ui/icarus/single', getattr(ui_icarus, 'IcarusSingleHandler')),


        # comm
        ('.*', getattr(comm, 'PageNotFoundHandler'))

    ]

    return config
